Uber/Models/Driver/DriverIndexViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Uber.Models.Driver
{
    public class DriverIndexViewModel
    {
        [Key]
        public int DriverId { get; set; }

        [Display(Name = "Driving Licence Id")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Your drving licence should be 10 symbols")]
        public string DrivingLicence { get; set; } = null!;

        [Display(Name = "Years of experience as a driver")]
        public int YearsOfExperience { get; set; }

        [Display(Name = "Vehicle categories that you are able to drive")]
        public IList<string> VehicleCategoriesLabels { get; set; } = null!;

        public double Latitude { get; set; }

        public double Longitude { get; set; }

        public bool IsApproved { get; set; }
    }
}

Uber/Models/Driver/ProceedOrderViewModel.cs
using NuGet.Protocol.Core.Types;
using System.ComponentModel.DataAnnotations;

namespace Uber.Models.Driver
{
    public class ProceedOrderViewModel
    {
        [Key]
        public int OrderId { get; set; }
        public string ClientName { get; set; } = null!;
        public double CurrentAddressLatitude { get; set; } 
        public double CurrentAddressLongitude { get; set; }
        public string CurrentAddressLabel { get; set; } = null!;
        public double DestinationAddressLatitude { get; set; }
        public double DestinationAddressLongitude { get; set; }
        public string DestinationAddressLabel { get; set; } = null!;
        public int CountOfSeats { get; set; }
    }
}

Uber/Controllers/DriverController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Uber.Core.Contracts;
using Uber.Core.Services;
using Uber.Models.Driver;

namespace Uber.Controllers
{
    [Authorize(Roles = "Admin, Driver, Client")]
    public class DriverController : Controller
    {
        private readonly IDriverService _driverService;
        private readonly IOrderService _orderService;
        private readonly IPersonService _personService;
        private readonly IClientService _clientService;
        private readonly IAddressService _addressService;

        public DriverController(IDriverService driverService, IOrderService orderService,
            IPersonService personService, IClientService clientService, IAddressService addressService)
        {
            _driverService = driverService;
            _orderService = orderService;
            _personService = personService;
            _clientService = clientService;
            _addressService = addressService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var drivers = await _driverService.GetAllDrivers();
            var vehicleLabels = new List<string>();
            
            var viewModel = new List<DriverIndexViewModel>();
            foreach (var driver in drivers)
            {
                vehicleLabels = driver.VehicleCategories.Select(x => x.Label).ToList();
                viewModel.Add(new DriverIndexViewModel()
                {
                    DriverId = driver.DriverId,
                    DrivingLicence = driver.DrivingLicence,
                    YearsOfExperience = driver.Experience,
                    VehicleCategoriesLabels = vehicleLabels,
                    Latitude = driver.CurrentPosition.Value.X,
                    Longitude = driver.CurrentPosition.Value.Y,
                    IsApproved = driver.IsDriverApproved
                });
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ProceedOrder(int driverId, int orderId)
        {
            if (driverId <= 0 || orderId <= 0)
            {
                return NotFound();
            }
            var driver = await _driverService.GetDriverByDriverId(driverId);
            var order = await _orderService.GetOrderById(orderId);
            if (driver == null)
            {
                return NotFound("Driver not found!");
            }
            if (order == null)
            {
                return NotFound("Order not found!");
            }
            var client = await _clientService.GetClientByClientId(order.ClientId);
            var person = await _personService.GetPersonByPersonId(client.PersonId);
            var currAddress = await _addressService.GetAddressById(order.CurrentAddressId);
            var destinationAddress = await _addressService.GetAddressById(order.DestinationId);
            ProceedOrderViewModel viewModel = new ProceedOrderViewModel()
            {
                OrderId = orderId,
                ClientName = person.FirstName + " " + person.LastName,
                CurrentAddressLabel = currAddress.Description,
                CurrentAddressLatitude = currAddress.Location.Value.Y,
                CurrentAddressLongitude = currAddress.Location.Value.X,
                DestinationAddressLabel = destinationAddress.Description,
                DestinationAddressLatitude = destinationAddress.Location.Value.Y,
                DestinationAddressLongitude = destinationAddress.Location.Value.X,
                CountOfSeats = order.CountOfPassengers
            };
            return View(viewModel);
        }
    }
}

Uber/Views/Driver/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@using Uber.Models.Driver;
@model IEnumerable<DriverIndexViewModel>;
@inject Microsoft.AspNetCore.Identity.UserManager<IdentityUser> _userManager;

<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>Driver - Index</title>
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/reset.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/site.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/container.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/grid.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/header.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/image.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/menu.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/divider.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/segment.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/form.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/input.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/button.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/list.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/message.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/icon.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/table.css">
</head>

<body>
    <table class="ui padded table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DrivingLicence)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.YearsOfExperience)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Longitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Latitude)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var user = await _userManager.GetUserAsync(User);
                bool isAdmin = await _userManager.IsInRoleAsync(user, "Admin");
                if (isAdmin || item.IsApproved) // here we are using the short-circuit evaluation of or expression
                {
                    <tr>
                        <td class="ui center aligned">
                            @Html.DisplayFor(modelItem => item.DrivingLicence)
                        </td>
                        <td class="ui center aligned">
                            @Html.DisplayFor(modelItem => item.YearsOfExperience)
                        </td>
                        <td class="ui center aligned">
                            @Html.DisplayFor(modelItem => item.Longitude)
                        </td>
                        <td class="ui center aligned">
                            @Html.DisplayFor(modelItem => item.Latitude)
                        </td>
                        <td class="ui center aligned">
                            @if (isAdmin && !item.IsApproved)
                            {
                                <a asp-action="ApproveDriver" asp-route-driverId="@item.DriverId" asp-controller="Admin">Approve</a>
                            }                           
                            @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                        </td>
                    </tr>
                }              
            }
        </tbody>
        <tfoot>
            <tr>

            </tr>
        </tfoot>
    </table>
</body>
</html>

Uber/Views/Driver/ProceedOrder.cshtml
@using Uber.Models.Driver;
@model ProceedOrderViewModel;
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>Driver - Proceed order</title>
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/reset.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/site.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/container.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/grid.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/header.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/image.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/menu.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/divider.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/segment.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/form.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/input.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/button.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/list.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/message.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fomantic-ui/dist/components/icon.css">
</head>

<body>
   @* <div class="ui middle aligned center aligned grid">*@
        <div class="column">
            <div class="ui center aligned segment">
                <h2 class="ui center aligned icon header">
                    <i class="orange clipboard list icon"></i>
                    Offered Order
                </h2>
                <div class="ui two column vertically divided grid">
                    <div class="row">
                        <div class="column middle aligned">
                            <h3 class="ui image label">
                                <img src="~/imagesDemo/clientIco.png">
                                Client Name
                            </h3>
                        </div>
                        <h3 class="column middle aligned">
                            @Model.ClientName
                        </h3>
                    </div>
                    <div class="row">
                        <div class="column middle aligned">
                            <h3 class="ui label">
                                <i class="teal address book icon"></i>
                                Current Address
                            </h3>
                        </div>
                        <h3 class="column">
                            @Model.CurrentAddressLabel ( @Model.CurrentAddressLatitude, @Model.CurrentAddressLongitude)
                        </h3>
                    </div>

                    <div class="row">
                        <div class="column">
                            <h3 class="ui label">
                                <i class="teal address book icon"></i>
                                Destination Address
                            </h3>
                        </div>
                        <h3 class="column">
                            @Model.DestinationAddressLabel ( @Model.DestinationAddressLatitude, @Model.DestinationAddressLongitude)
                        </h3>
                    </div>

                    <div class="row">
                        <div class="column">
                            <h3 class="ui label">
                                <i class="car icon"></i>
                                Seats
                            </h3>
                        </div>
                        <h3 class="column">
                            @Model.CountOfSeats
                        </h3>
                    </div>
                </div>
            <div class="ui section horizontal divider">@* TODO*@
                
            </div>
            <div class="ui two column divided grid">
                <div class="column">
                    <button class="ui orrange button" asp-action="AcceptOrder" asp-controller="Driver">
                        Accept
                    </button>
                </div><div class="column">
                    <button class="ui orrange button" asp-action="DeclineOrder" asp-controller="Driver">
                       Decline
                    </button>
                </div>
            </div>
            </div>
        </div>
  @*  </div>*@
</body>
</html>